[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "gardener-cicd-libs>=1.2683.0",
    "modelo>=0.0.3",
]
